name: GitGuardian Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  gitguardian_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install GitGuardian CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo apt install python3-pip
          pip install ggshield
      
      - name: Authenticate with GitGuardian
        env:
          GGSHIELD_API_KEY: ${{ secrets.GGSHIELD_API_KEY }}
        run: ggshield auth --api-key $GGSHIELD_API_KEY
      
      - name: Scan repository with GitGuardian
        run: ggshield scan --no-colors --no-progress
      
      - name: Fail if issues found
        run: ggshield status --exit-code
